//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WISData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WISEntities : DbContext
    {
        public WISEntities()
            : base("name=WISEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblItemCategory> tblItemCategories { get; set; }
        public virtual DbSet<tblLocation> tblLocations { get; set; }
        public virtual DbSet<tblItemInventoryAudit> tblItemInventoryAudits { get; set; }
        public virtual DbSet<tblClientType> tblClientTypes { get; set; }
        public virtual DbSet<tblInvoice> tblInvoices { get; set; }
        public virtual DbSet<tblItemInventory> tblItemInventories { get; set; }
        public virtual DbSet<tblEmployeeLocation> tblEmployeeLocations { get; set; }
        public virtual DbSet<tblExternalClient> tblExternalClients { get; set; }
        public virtual DbSet<tblInvoiceSummary> tblInvoiceSummaries { get; set; }
        public virtual DbSet<tblEmployee> tblEmployees { get; set; }
        public virtual DbSet<tblInvoiceDetail> tblInvoiceDetails { get; set; }
        public virtual DbSet<tblJob> tblJobs { get; set; }
    }
}
