//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WISData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEstimate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEstimate()
        {
            this.tblEstimateDetails = new HashSet<tblEstimateDetail>();
        }
    
        public int EstimateId { get; set; }
        public string EstimateNumber { get; set; }
        public System.DateTime EstimateDate { get; set; }
        public string ClientName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Status { get; set; }
        public Nullable<int> ExternalClientID { get; set; }
        public Nullable<int> ClientTypeID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string Vendor_ { get; set; }
        public string VendoeEstimate { get; set; }
        public string EstimateTerms { get; set; }
        public string EstimateNotes { get; set; }
        public string CreatedUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEstimateDetail> tblEstimateDetails { get; set; }
    }
}
