//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WISData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvoiceDetail
    {
        public int InvoiceDetailID { get; set; }
        public int InvoiceID { get; set; }
        public Nullable<int> ItemInventoryID { get; set; }
        public string ItemInventoryDescription { get; set; }
        public string NonInventoryItem { get; set; }
        public string InvoiceDetailCostCodeGL { get; set; }
        public Nullable<decimal> ItemInventoryUnitCost { get; set; }
        public Nullable<int> InvoiceDetailQuantity { get; set; }
        public Nullable<decimal> InvoiceDetailLineItemTotal { get; set; }
    
        public virtual tblItemInventory tblItemInventory { get; set; }
        public virtual tblInvoice tblInvoice { get; set; }
    }
}
