//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WISData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvoiceSummary
    {
        public decimal InvoiceSummaryTotal0To30 { get; set; }
        public decimal InvoiceSummaryTotal31To60 { get; set; }
        public decimal InvoiceSummaryTotal61To90 { get; set; }
        public decimal InvoiceSummaryTotal91Plus { get; set; }
        public decimal InvoiceSummaryTotalAll { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    }
}
