//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WISData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblInvoice()
        {
            this.tblInvoiceDetails = new HashSet<tblInvoiceDetail>();
        }
    
        public int InvoiceID { get; set; }
        public string InvoiceNumber { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string InvoiceJobNumber { get; set; }
        public string InvoicePONumber { get; set; }
        public Nullable<decimal> InvoiceTotal { get; set; }
        public string InvoiceTerms { get; set; }
        public string InvoiceNotes { get; set; }
        public string InvoiceStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> ExternalClientID { get; set; }
        public Nullable<int> ClientTypeID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string InvoiceOrderedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInvoiceDetail> tblInvoiceDetails { get; set; }
    }
}
